Some miscellaneous things
flex3r/DankChat pull request #100
Opened 2020-10-22 02:01 UTC by TacoTheDank

Sup.

### 1st commit
- Updated Constraint to 2.0.2
- Remove unused Koin

### 2nd commit
- Switch to SwitchPreferenceCompat (no difference, really, but why not)

### 3rd commit
- Don't reserve icon space for settings without icons (this makes the settings look better padding and margin-wise)

### 4th commit
- Remove unused drawables
- Renamed and regenerated drawables

### 5th commit
- Use some KTX extensions

### 6th commit
- Some code lint refactoring

### 7th commit
- Optimize PNGs using https://ezgif.com/optipng

2020-10-22 18:28 UTC, flex3r requested changes
First of all, thanks for the pr, definitely some nice changes in there!
However some of your changes caused crashes right after app launch, please make sure to test them yourself next time 🙂

2020-10-22 18:28 UTC, flex3r commented on app/src/main/kotlin/com/flxrs/dankchat/chat/mention/MentionChatFragment.kt
> +            else -> viewModel.mentions.observe(viewLifecycleOwner, adapter::submitList)
Crashes because adapter is a lateinit var

2020-10-22 18:28 UTC, flex3r commented on app/src/main/kotlin/com/flxrs/dankchat/chat/mention/MentionChatFragment.kt
> +            isWhisperTab -> viewModel.whispers.observe(viewLifecycleOwner, adapter::submitList)
Crashes because adapter is a lateinit var

2020-10-22 18:28 UTC, flex3r commented on app/src/main/res/xml/appearance_settings.xml
> +    <SwitchPreferenceCompat
This wasn't even a SwitchPreference ???

2020-10-22 18:28 UTC, flex3r commented on app/src/main/res/xml/chat_settings.xml
> +        <SwitchPreferenceCompat
Same as before, this was a SeekBarPreference, not a SwitchPreference

2020-10-22 18:28 UTC, flex3r commented on app/src/main/res/drawable/ic_notifications_active.xml
> -        android:fillColor="?attr/colorControlNormal"
This was intentional to make it more clear that there are no unseen mentions

2020-10-22 18:28 UTC, flex3r commented on app/src/main/res/drawable/ic_missing_emote.xml
> +        android:fillColor="@android:color/white"
Revert back to black please

2020-10-23 23:17 UTC, TacoTheDank commented on app/src/main/res/xml/appearance_settings.xml
> +    <SwitchPreferenceCompat
No idea how I missed that 🤦

2020-10-23 23:19 UTC, TacoTheDank commented on build.gradle
> +        constraint_version = '2.0.2'
Hmm

2020-10-23 23:27 UTC, TacoTheDank commented on app/src/main/kotlin/com/flxrs/dankchat/DankChatApplication.kt
> +        val uiModeManager = getSystemService<UiModeManager>()!!
Alright

2020-10-23 23:40 UTC, TacoTheDank commented
Lol sorry about that

2020-10-24 11:06 UTC, flex3r approved these changes
Looks good now, thanks 👍

2020-10-24 11:08 UTC, merged