Created values-cs.xml
flex3r/DankChat pull request #107
Opened 2020-12-22 20:30 UTC by MrJaroslavik

Czech translation added. Can you please create folder for it and rename this to strings.xml

2020-12-23 21:13 UTC, flex3r commented
Not sure why I should do that, but sure. Also, strings marked as `translatable="false"` should not be translated or added to the file.  
Looks good otherwise, I'll have some others look over the translations and get back to you 👍

2020-12-23 21:27 UTC, MrJaroslavik commented
Oh sorry, this is why in other languages is only 145 lines :D. I thought it should be there, sorry for that. And question: Where is language change option or it will be in some upcoming update? Thanks.

2020-12-23 21:28 UTC, MrJaroslavik commented
And why - i wasn't able to create folder.

2020-12-23 21:29 UTC, flex3r commented
There's no language option in DankChat right now, the app will use what language is set in the OS.

2020-12-23 22:06 UTC, fabZeef requested changes
Fixed some errors in translate

2020-12-23 22:06 UTC, fabZeef commented on app/src/main/res/values-cz/strings.xml
> +    <string name="preference_debug_mode_summary">Poskytuje informace o všech výjimkách, které byly zachyceny</string>
Poskytuje informace o všech chybách, které byly zachyceny

2020-12-23 22:06 UTC, fabZeef commented on app/src/main/res/values-cz/strings.xml
> +    <string name="preference_tts_queue_title">Režim fronty zpráv</string>
Režim čtení bez přerušování

2020-12-23 22:06 UTC, fabZeef commented on app/src/main/res/values-cz/strings.xml
> +    <string name="preference_tts_queue_add">Hrát každou zprávu s použitím fronty</string>
Čte každou zprávu s použitím fronty

2020-12-23 22:06 UTC, fabZeef commented on app/src/main/res/values-cz/strings.xml
> +    <string name="preference_tts_queue_flush">Hrát pouze nejnovější zprávu</string>
Čte pouze nejnovější zprávu

2020-12-23 22:06 UTC, fabZeef commented on app/src/main/res/values-cz/strings.xml
> +    <string name="preference_tts_message_format_title">Formát režimu zpráv</string>
Formát režimu čtení zpráv

2020-12-23 22:06 UTC, fabZeef commented on app/src/main/res/values-cz/strings.xml
> +    <string name="preference_checkered_lines_title">Kostkované Řádky</string>
Kostkované řádky

2021-01-06 18:00 UTC, flex3r commented
@MrJaroslavik any progress on this?

2021-02-14 16:22 UTC, merged