Updated serbian translation
flex3r/DankChat pull request #204
Opened 2022-01-05 19:03 UTC by CommName

2022-01-08 17:45 UTC, flex3r commented
I've added some additional ones since I also added single message deletion to the user popup. 
Can you add those as well? Looks good apart from that
```xml
<string name="user_popup_delete">Delete message</string>
<string name="confirm_user_delete_title">Confirm message deletion</string>
<string name="confirm_user_delete_message">Are you sure you want to delete this message?</string>
<string name="confirm_user_delete_positive_button">Delete</string>
```

2022-01-08 18:32 UTC, CommName commented
Updated :)

2022-01-08 19:39 UTC, flex3r requested changes

2022-01-08 19:39 UTC, flex3r commented on app/src/main/res/values-sr/strings.xml
> +    <string name="uploader_description">"Možete da podestie host za "</string>
Looks like this one is incomplete

2022-01-08 19:39 UTC, flex3r commented on app/src/main/res/values-sr/strings.xml
> +    <string name="restart_required">"Potrebno je restartovati aplikaciju da biste promenili promene "</string>
```suggestion
    <string name="restart_required">Potrebno je restartovati aplikaciju da biste promenili promene</string>
```

2022-01-14 16:08 UTC, CommName commented
I made suggested changes. Sorry for taking too long, I was unavailable for the last week due to holidays

2022-01-14 18:16 UTC, flex3r approved these changes
All good, hope you enjoyed your holidays

2022-01-14 18:16 UTC, merged