make Timestamp text monospace
flex3r/DankChat pull request #335
Opened 2022-10-04 10:19 UTC by rod41732

Fix #280 

Timestamp text in various place is changed to monospaced
- normal message (both in normal chat room and mention bottom sheet)  
- system message
- clear chat message
- redemption message (e.g. subs)
- whisper message (whisper tab)

2022-10-04 10:23 UTC, rod41732 commented
seeing that the refactor PR is have also change 
 the ChatAdapter file (https://github.com/flex3r/DankChat/pull/332/files#diff-89210ff4e83e5e148c385671a637272f24836783edc3e9aaa4b75cbd34e30fa4)

There might be small extra works after merging (to make sure all `handleXxxxxxMessage` correctly create monospaced text span for timestamp part of the message

2022-10-04 18:11 UTC, flex3r requested changes
Before I comment about the sizing that was chosen, can you add before and after screenshots?

2022-10-04 18:11 UTC, flex3r commented on app/src/main/kotlin/com/flxrs/dankchat/chat/ChatAdapter.kt
> +    private fun makeTimestampSpanStyles(context: Context): Array<CharacterStyle> {
I would prefer an inline extension function similar to the existing ones, like the ` bold` one. Returning an array and having to spread it for the `inSpans()` is just ugly xD

2022-10-05 04:13 UTC, rod41732 commented
Screenshots. Not embedding directly here since GitHub display image as very large  
- Before    
[Screenshot_20221005-110913_DankChat](https://user-images.githubusercontent.com/26536811/193979736-0c564cef-d32f-4215-9ff8-5caad5b30cd3.png)
- After
[Screenshot_20221005-110901_DankChat (Dank)](https://user-images.githubusercontent.com/26536811/193979779-eb7791a4-f826-4615-88da-77110dd3c048.png)

2022-10-05 17:09 UTC, flex3r commented
> Screenshots. Not embedding directly here since GitHub display image as very large
> 
> * Before
>   [Screenshot_20221005-110913_DankChat](https://user-images.githubusercontent.com/26536811/193979736-0c564cef-d32f-4215-9ff8-5caad5b30cd3.png)
> * After
>   [Screenshot_20221005-110901_DankChat (Dank)](https://user-images.githubusercontent.com/26536811/193979779-eb7791a4-f826-4615-88da-77110dd3c048.png)

The main thing I currently don't like is the increased gap between the time and the badges.. Do you have an idea of how to prevent that?

2022-10-06 02:59 UTC, rod41732 commented
We could remove the space inside the timestamp, then add another span after the timestamp with "normal" font. 
This should make the space same as before we changed the timestamp to monospace.

Feels a bit like a "hack" solution tho

2022-10-06 03:28 UTC, rod41732 commented on app/src/main/res/values/styles.xml
> +        <item name="android:letterSpacing">-0.03</item>
Not super important, bur it's looks "nicer" IMO. I feel that monospace font is a bit too wide and spaced so I make its width more inline with normal font.

Have tried using ScaleX span or something, didn't look as nice as this IMO.

- without letterSpacing change
[Screenshot_20221006-101716.png](https://user-images.githubusercontent.com/26536811/194207311-04558b49-f6a1-4b1b-8a69-01cf6e109e95.png)

- with letterSpacing
![Screenshot_20221006-101910.png](https://user-images.githubusercontent.com/26536811/194207379-b5a1b177-d3aa-4e6e-b4b0-8a999bcb4019.png)

Just me being to nitpicky LuL

2022-10-06 04:51 UTC, rod41732 commented
This is how it looks like using proposed solution in my previous comment
[image](https://user-images.githubusercontent.com/26536811/194216996-0b7e35c4-a96b-405a-bd05-410605ab901a.png)

2022-10-06 17:31 UTC, flex3r commented on app/src/main/res/values/styles.xml
> +        <item name="android:letterSpacing">-0.03</item>
Isn't that the point of monospace though? I'm fine with the fontSize change I guess, but let's revert this one

2022-10-06 17:32 UTC, flex3r commented on app/src/main/kotlin/com/flxrs/dankchat/utils/extensions/SpannableStringBuilderExtensions.kt
> +fun SpannableStringBuilder.addSpacing(): SpannableStringBuilder = append(" ")
Add the spacing directly in the timestamp extension function instead of introducing a new one

2022-10-06 17:34 UTC, flex3r commented on app/src/main/kotlin/com/flxrs/dankchat/utils/extensions/SpannableStringBuilderExtensions.kt
> +    RelativeSizeSpan(0.95f),
Extract this value to a constant please. I'm also fine with moving the function to the ChatAdapter file to have all the ui details there at one place

2022-10-10 17:00 UTC, flex3r commented on app/src/main/res/values/dimens.xml
> +    <item name="monospace_letter_spacing_adjustment" type="dimen" format="float">-0.03</item>
Current value causes some overlapping on small font sizes (13 in my case)
![image](https://user-images.githubusercontent.com/10165657/194918082-6459886e-c641-450b-ac2b-c168b927299a.png)

2022-10-11 08:30 UTC, flex3r approved these changes
LGTM ![image](https://user-images.githubusercontent.com/10165657/121775266-e4d2ab80-cb86-11eb-9df5-c953f41fec2e.png)

2022-10-11 08:30 UTC, merged